// Descripciones honestas + fixes de datos para los 158 productos a crear en Tanda 3.
// Regla: nada de puntajes/premios/notas de cata inventadas. Region solo si es de conocimiento
// general confiable (bodegas grandes/reconocidas); si no, descripcion generica varietal+categoria+bodega.

const CAT_TXT = { Tinto: 'vino tinto', Blanco: 'vino blanco', Rosado: 'vino rosado', Espumante: 'vino espumante' }

function base(nombre, bodega, varietal, categoria, notas) {
  let s = `${nombre} es un ${CAT_TXT[categoria] || 'vino'}`
  if (varietal && varietal.toLowerCase() !== 'blend') s += ` elaborado con uvas ${varietal}`
  else if (varietal && varietal.toLowerCase() === 'blend') s += ' de corte (blend)'
  if (bodega) s += `, producido por ${bodega}`
  s += '.'
  if (notas) s += ` ${notas}`
  return s
}

// { descripcion, categoriaFix?, varietalFix?, bodegaFix?, extraTags? }
export const OVERRIDES = {
  'Tapiz Bonarda': { descripcion: base('Tapiz Bonarda', 'Bodega Tapiz', 'Bonarda', 'Tinto', 'Bodega Tapiz elabora sus vinos en Agrelo y el Valle de Uco, Mendoza.') },
  'Altus Reserva Merlot Gualtallary': { descripcion: base('Altus Reserva Merlot', 'Gualtallary Wines', 'Merlot', 'Tinto', 'Línea Reserva de Altus, de viñedos en Gualtallary, Valle de Uco.') },
  'Malma Malbec': { descripcion: base('Malma Malbec', 'Malma', 'Malbec', 'Tinto', 'Malma es una bodega patagónica, con viñedos en la región del Río Negro.') },
  'Canale Estate Blend': { descripcion: base('Canale Estate Blend', 'Humberto Canale', 'Blend', 'Tinto', 'Línea Estate de Bodega Humberto Canale, pionera del Alto Valle de Río Negro, Patagonia.'), bodegaFix: 'Humberto Canale' },
  'Clos de Cal 2021': { descripcion: base('Clos de Cal 2021', null, 'Blend', 'Tinto', 'Corte de guarda de la cosecha 2021.') },
  'Coursair Garnacha': { descripcion: base('Coursair Garnacha', null, 'Garnacha', 'Tinto'), varietalFix: 'Garnacha' },
  'Conejo Verde Brut Rose': { descripcion: `Conejo Verde Brut Rose es un espumante rosado. Forma parte de la línea "Conejo" de vinos frescos y de estilo desenfadado.`, categoriaFix: 'Espumante' },
  'Cuesta Del Madero Roble Cab. Sauv.': { descripcion: base('Cuesta del Madero Roble Cabernet Sauvignon', 'Cuesta del Madero', 'Cabernet Sauvignon', 'Tinto', 'Paso por roble, línea de entrada de la bodega.') },
  'Iaccarini Via Blanca Malbec': { descripcion: base('Iaccarini Via Blanca Malbec', 'Iaccarini', 'Malbec', 'Tinto', 'Línea Via Blanca de Bodega Iaccarini.') },
  'Humbeto Canale estate Malbec': { descripcion: base('Humberto Canale Estate Malbec', 'Humberto Canale', 'Malbec', 'Tinto', 'Bodega Humberto Canale, pionera del Alto Valle de Río Negro, Patagonia. Línea Estate.'), bodegaFix: 'Humberto Canale' },
  'Misterio Malbec': { descripcion: base('Misterio Malbec', 'Finca Flichman', 'Malbec', 'Tinto', 'Línea Misterio de Finca Flichman, bodega mendocina fundada en 1910.') },
  'Cinzano Bianco': { descripcion: 'Cinzano Bianco es un vermut blanco dulce de origen italiano (Turín), elaborado con vino aromatizado con hierbas y especias. Ideal solo, con hielo o como base de cócteles.' },
  'Gimenez Riili Grapa': { descripcion: 'Grapa de Bodega Gimenez Riili, aguardiente destilado de orujo de uva (bagazo), siguiendo la tradición itálica de la grappa.', categoriaFix: 'Otro' },
  'Contra Viento Fuego Blanco': { descripcion: base('Contra Viento', 'Fuego Blanco', 'Blend', 'Tinto', 'Corte de la bodega patagónica Fuego Blanco.') },
  'Iaccarini Via Blanca Red Blend': { descripcion: base('Iaccarini Via Blanca Red Blend', 'Iaccarini', 'Blend', 'Tinto', 'Línea Via Blanca de Bodega Iaccarini, corte de tintas.') },
  'Iaccarini Via Blanca Syrah': { descripcion: base('Iaccarini Via Blanca Syrah', 'Iaccarini', 'Syrah', 'Tinto', 'Línea Via Blanca de Bodega Iaccarini.') },
  'Iaccarini Via Blanca Bonarda': { descripcion: base('Iaccarini Via Blanca Bonarda', 'Iaccarini', 'Bonarda', 'Tinto', 'Línea Via Blanca de Bodega Iaccarini.') },
  'Cinzano 1757 Extra Dry': { descripcion: 'Cinzano 1757 Extra Dry es un vermut blanco seco de origen italiano, línea premium de Cinzano (nombre en referencia al año de fundación de la casa, 1757).' },
  'Foster Caja de Madera x6 (Malbec y Bonarda)': { descripcion: 'Estuche de madera con 6 botellas de la línea premium "Firmado" de Enrique Foster (combinación Malbec y Bonarda), bodega de Perdriel, Luján de Cuyo, Mendoza.' },
  'Lorca Caja de Madera x6 Inspirado (Blend, Cab.Cab, Cab.Franc)': { descripcion: 'Estuche de madera con 6 botellas de la línea "Inspirado" de Bodega Lorca, combinando corte, Cabernet Sauvignon y Cabernet Franc.' },
  'Iaccarini Via Blanca Terroir Selec. C Suavign': { descripcion: base('Iaccarini Via Blanca Terroir Selección Cabernet Sauvignon', 'Iaccarini', 'Cabernet Sauvignon', 'Tinto', 'Línea Terroir Selección de Via Blanca, Bodega Iaccarini.') },
  'Iaccarini Via Blanca White Blend': { descripcion: base('Iaccarini Via Blanca White Blend', 'Iaccarini', 'Blend', 'Blanco', 'Línea Via Blanca de Bodega Iaccarini, corte de blancas.') },
  'Iaccarini Via Blanca Terroir Selec. Malbec': { descripcion: base('Iaccarini Via Blanca Terroir Selección Malbec', 'Iaccarini', 'Malbec', 'Tinto', 'Línea Terroir Selección de Via Blanca, Bodega Iaccarini.') },
  'Iaccarini Via Blanca Terroir Selection Chenin': { descripcion: base('Iaccarini Via Blanca Terroir Selection Chenin', 'Iaccarini', 'Chenin Blanc', 'Blanco', 'Línea Terroir Selección de Via Blanca, Bodega Iaccarini.'), categoriaFix: 'Blanco', varietalFix: 'Chenin Blanc' },
  'Martini Rosso': { descripcion: 'Martini Rosso es un vermut rojo dulce de origen italiano, uno de los más reconocidos del mundo, elaborado con vino aromatizado con hierbas y especias.' },
  'Martini Extra Dry': { descripcion: 'Martini Extra Dry es un vermut blanco seco de origen italiano, ideal para cócteles clásicos como el martini seco.' },
  'Altus Merlot Gualtallary': { descripcion: base('Altus Merlot', 'Gualtallary Wines', 'Merlot', 'Tinto', 'De viñedos en Gualtallary, Valle de Uco.') },
  'J&B 750 Cc': { descripcion: 'J&B Rare es un whisky escocés blended, de Justerini & Brooks, marca fundada en Londres en 1749.' },
  'Grants Litro': { descripcion: 'Grant\'s es un whisky escocés blended de la casa William Grant & Sons, en botella de 1 litro.' },
  'Branca Menta 750': { descripcion: 'Branca Menta es un licor amargo con menta de Fratelli Branca Distillerie (Milán, Italia), variante del clásico Fernet Branca, muy popular en Argentina.' },
  'Punt E Mes': { descripcion: 'Punt e Mes es un vermut rojo con mayor amargor, de la casa Carpano (Turín, Italia), creadora del vermut moderno en 1786.' },
  'Borghetti': { descripcion: 'Caffè Borghetti es un licor de café italiano, elaborado con café espresso, de la casa Borghetti (Módena, Italia).' },
  'Cinzano Rosso': { descripcion: 'Cinzano Rosso es un vermut rojo dulce de origen italiano (Turín), elaborado con vino aromatizado con hierbas y especias.' },
  'Altus Extra Brut Gualtallary': { descripcion: base('Altus Extra Brut', 'Gualtallary Wines', null, 'Espumante', 'Espumante de la línea Altus, de viñedos en Gualtallary, Valle de Uco.') },
  'Altus Grand Vin Gualtallary': { descripcion: base('Altus Grand Vin', 'Gualtallary Wines', 'Blend', 'Tinto', 'Línea tope de gama de Altus, de viñedos en Gualtallary, Valle de Uco.') },
  'Cinzano 1757 Rosso': { descripcion: 'Cinzano 1757 Rosso es un vermut rojo dulce de origen italiano, línea premium de Cinzano (nombre en referencia al año de fundación de la casa, 1757).' },
  'Acordeón Malbec': { descripcion: base('Acordeón Malbec', 'Finca Ferrer', 'Malbec', 'Tinto', 'Línea Acordeón de Finca Ferrer.') },
  'Cara Sucia Sangiovese': { descripcion: base('Cara Sucia Sangiovese', null, 'Sangiovese', 'Tinto') },
  'Cara Sucia Nebbiolo': { descripcion: base('Cara Sucia Nebbiolo', null, 'Nebbiolo', 'Tinto'), varietalFix: 'Nebbiolo' },
  'Acordeón Cabernet Sauvignon': { descripcion: base('Acordeón Cabernet Sauvignon', 'Finca Ferrer', 'Cabernet Sauvignon', 'Tinto', 'Línea Acordeón de Finca Ferrer.') },
  'Wild Africa Chocolate': { descripcion: 'Wild Africa Chocolate es un licor cremoso sabor chocolate, estilo crema de licor sudafricana.', bodegaFix: null },
  'Belladona Dry Gin Andina': { descripcion: 'Belladona es un gin artesanal argentino elaborado con botánicos andinos.' },
  'Pacheco Pereda Malbec': { descripcion: base('Pacheco Pereda Malbec', null, 'Malbec', 'Tinto') },
  'Los Bocheros Cabernet Sauvignon': { descripcion: base('Los Bocheros Cabernet Sauvignon', 'Los Bocheros', 'Cabernet Sauvignon', 'Tinto') },
  'Conejo Verde Malbec Falasco': { descripcion: 'Conejo Verde Malbec es un vino tinto elaborado con uvas Malbec, de la línea "Conejo" de Falasco Family Wines, bodega mendocina.', bodegaFix: 'Falasco Wines' },
  'Il Caprone Malbec': { descripcion: base('Il Caprone Malbec', 'Bodegas Bianchi', 'Malbec', 'Tinto', 'Línea de entrada de Bodegas Bianchi, San Rafael, Mendoza.') },
  'Gsm Trapiche': { descripcion: base('GSM Trapiche', 'Trapiche', 'Blend', 'Tinto', 'Corte estilo GSM (Garnacha-Syrah-Mourvèdre) de Bodega Trapiche, Mendoza.') },
  'Cuesta Del Madero Roble Malbec': { descripcion: base('Cuesta del Madero Roble Malbec', 'Cuesta del Madero', 'Malbec', 'Tinto', 'Paso por roble, línea de entrada de la bodega.') },
  'Wine Records Lata': { descripcion: 'Wine Records es un vino tinto en formato lata, práctico y de consumo individual.' },
  'Wild Africa Cream': { descripcion: 'Wild Africa Cream es un licor cremoso, estilo crema de licor sudafricana (similar a Amarula).' },
  'Carpano': { descripcion: 'Carpano Classico es el vermut rojo original de la casa Carpano (Turín, Italia), creadora del vermut moderno en 1786.' },
  'Altus Chardonnay Gualtallary Wines': { descripcion: base('Altus Chardonnay', 'Gualtallary Wines', 'Chardonnay', 'Blanco', 'De viñedos en Gualtallary, Valle de Uco.'), varietalFix: 'Chardonnay' },
  'Anis Shami': { descripcion: 'Anís Shami es un licor de anís, tradicional en la coctelería y sobremesa argentina.' },
  'Evan Williams Black': { descripcion: 'Evan Williams Black Label es un bourbon whiskey de Kentucky, EE.UU., de la destilería Heaven Hill.' },
  'Linea 581 Cabernet Sauvignon Staphyle': { descripcion: base('Línea 581 Cabernet Sauvignon', 'Staphyle', 'Cabernet Sauvignon', 'Tinto', 'Línea 581 de Bodega Staphyle.') },
  'Linea 581 Torrontes Staphyle': { descripcion: base('Línea 581 Torrontés', 'Staphyle', 'Torrontés', 'Blanco', 'Línea 581 de Bodega Staphyle.'), varietalFix: 'Torrontés' },
  'Linea 581 Malbec Staphyle': { descripcion: base('Línea 581 Malbec', 'Staphyle', 'Malbec', 'Tinto', 'Línea 581 de Bodega Staphyle.') },
  'Argento Reserve Malbec': { descripcion: base('Argento Reserve Malbec', 'Argento', 'Malbec', 'Tinto', 'Bodega Argento, Mendoza.') },
  'Antonieta Rose de Pinot Noir': { descripcion: base('Antonieta Rosé de Pinot Noir', 'Falasco Family Wines', 'Pinot Noir', 'Rosado', 'Falasco Family Wines, bodega mendocina.'), bodegaFix: 'Falasco Wines' },
  'Argento Artesano Malbec Orgánico': { descripcion: base('Argento Artesano Malbec Orgánico', 'Argento', 'Malbec', 'Tinto', 'Línea Artesano de Argento, elaborado con uvas de cultivo orgánico certificado.') },
  'Chito Homenaje Raboso Los Mateines': { descripcion: 'Chito Homenaje Raboso es un vino tinto de Finca Los Mateines, elaborado con la variedad italiana Raboso.', varietalFix: 'Raboso' },
  '45° Rugientes Pinot Noir Otronia': { descripcion: base('45 Rugientes Pinot Noir', 'Otronia', 'Pinot Noir', 'Tinto', 'Otronia es el proyecto de Familia Zuccardi en Chubut, Patagonia, a la latitud 45° (paralelo de los "45 Rugientes"), uno de los viñedos más australes del mundo.'), varietalFix: 'Pinot Noir' },
  '45° Rugientes Merlot Otronia': { descripcion: base('45 Rugientes Merlot', 'Otronia', 'Merlot', 'Tinto', 'Otronia es el proyecto de Familia Zuccardi en Chubut, Patagonia, a la latitud 45° (paralelo de los "45 Rugientes"), uno de los viñedos más australes del mundo.'), varietalFix: 'Merlot' },
  'Ferraro Wines Reserva Malbec': { descripcion: base('Ferraro Wines Reserva Malbec', 'Ferraro Wines', 'Malbec', 'Tinto') },
  'Ferraro Wines Reserva Carmere': { descripcion: base('Ferraro Wines Reserva Carménère', 'Ferraro Wines', 'Carménère', 'Tinto'), varietalFix: 'Carménère' },
  'Malma Pinot Noir Finca La Papay': { descripcion: base('Malma Pinot Noir Finca La Papay', 'Malma', 'Pinot Noir', 'Tinto', 'Malma es una bodega patagónica de la región del Río Negro.') },
  'Malma Sauvignon Blanc': { descripcion: base('Malma Sauvignon Blanc', 'Malma', 'Sauvignon Blanc', 'Blanco', 'Malma es una bodega patagónica de la región del Río Negro.') },
  'Ferraro Wines Reserva Blend': { descripcion: base('Ferraro Wines Reserva Blend', 'Ferraro Wines', 'Blend', 'Tinto') },
  'Ferraro Wines Classic Malbec': { descripcion: base('Ferraro Wines Classic Malbec', 'Ferraro Wines', 'Malbec', 'Tinto', 'Línea Classic, de entrada, de Ferraro Wines.') },
  'Animal Colours Malbec': { descripcion: base('Animal Colours Malbec', null, 'Malbec', 'Tinto') },
  'Huella Pampa Malbec': { descripcion: base('Huella Pampa Malbec', 'Huella Pampa', 'Malbec', 'Tinto') },
  'Huella Pampa Roble Cabernet Sauvignon': { descripcion: base('Huella Pampa Roble Cabernet Sauvignon', 'Huella Pampa', 'Cabernet Sauvignon', 'Tinto', 'Con paso por roble.') },
  'Huella Pampa Roble Malbec': { descripcion: base('Huella Pampa Roble Malbec', 'Huella Pampa', 'Malbec', 'Tinto', 'Con paso por roble.') },
  'Animal Syrah': { descripcion: base('Animal Syrah', null, 'Syrah', 'Tinto') },
  'Jardin Enchante Rosado': { descripcion: base('Jardín Enchanté Rosado', null, 'Merlot', 'Rosado') },
  'Mara de Uco Pinot Noir': { descripcion: base('Mara de Uco Pinot Noir', 'Mara', 'Pinot Noir', 'Tinto', 'De viñedos del Valle de Uco.') },
  'Mara de Uco Petit Verdot': { descripcion: base('Mara de Uco Petit Verdot', 'Mara', 'Petit Verdot', 'Tinto', 'De viñedos del Valle de Uco.') },
  'Pequeñas Producciones Malbec': { descripcion: 'Pequeñas Producciones Malbec es un vino tinto elaborado con uvas Malbec, de una edición de producción limitada.' },
  'Pequeñas Producciones Syrah': { descripcion: 'Pequeñas Producciones Syrah es un vino tinto elaborado con uvas Syrah, de una edición de producción limitada.' },
  'Fuzion Malbec': { descripcion: base('Fuzion Malbec', 'Fuzion (Familia Zuccardi)', 'Malbec', 'Tinto', 'Línea de entrada de Familia Zuccardi.') },
  'Pequeñas Producciones Chardonnay': { descripcion: 'Pequeñas Producciones Chardonnay es un vino blanco elaborado con uvas Chardonnay, de una edición de producción limitada.' },
  'Pequeñas Producciones Franc': { descripcion: 'Pequeñas Producciones Cabernet Franc es un vino tinto elaborado con uvas Cabernet Franc, de una edición de producción limitada.', varietalFix: 'Cabernet Franc' },
  'Pequeñas Producciones Barbera': { descripcion: 'Pequeñas Producciones Barbera es un vino tinto elaborado con uvas Barbera, de una edición de producción limitada.' },
  'Alambrado Chardonnay': { descripcion: base('Alambrado Chardonnay', 'Santa Julia', 'Chardonnay', 'Blanco', 'Línea Alambrado de Santa Julia (Familia Zuccardi), Mendoza.') },
  'Pequeñas Producciones Pinot Noir': { descripcion: 'Pequeñas Producciones Pinot Noir es un vino tinto elaborado con uvas Pinot Noir, de una edición de producción limitada.' },
  'Alambrado Bonarda': { descripcion: base('Alambrado Bonarda', 'Santa Julia', 'Bonarda', 'Tinto', 'Línea Alambrado de Santa Julia (Familia Zuccardi), Mendoza.') },
  'Santa Julia Chenin Dulce': { descripcion: base('Santa Julia Chenin Dulce', 'Santa Julia', 'Chenin', 'Blanco', 'Santa Julia (Familia Zuccardi), Mendoza. Estilo dulce/semidulce.'), varietalFix: 'Chenin' },
  'Alambrado Cabernet Franc': { descripcion: base('Alambrado Cabernet Franc', 'Santa Julia', 'Cabernet Franc', 'Tinto', 'Línea Alambrado de Santa Julia (Familia Zuccardi), Mendoza.') },
  'Texto Súbito Cab. Suavig - P.T Verd. Los Helechos': { descripcion: 'Texto Súbito Cabernet Sauvignon - Petit Verdot es un corte tinto de Finca Los Helechos.', varietalFix: 'Blend' },
  'Texto Súbito Malb-Cab. Franc Los Helechos': { descripcion: 'Texto Súbito Malbec - Cabernet Franc es un corte tinto de Finca Los Helechos.', varietalFix: 'Blend' },
  'La Fuerza Rojo 10 Lt': { descripcion: 'La Fuerza Vermouth Rojo en formato de 10 litros. Vermut rojo dulce, ideal para bares y consumo por copeo.' },
  'Newen Merlot': { descripcion: base('Newen Merlot', 'Bodega del Fin del Mundo', 'Merlot', 'Tinto', 'Línea Newen (de entrada) de Bodega del Fin del Mundo, San Patricio del Chañar, Neuquén, Patagonia.') },
  'Newen Pinot Noir': { descripcion: base('Newen Pinot Noir', 'Bodega del Fin del Mundo', 'Pinot Noir', 'Tinto', 'Línea Newen (de entrada) de Bodega del Fin del Mundo, San Patricio del Chañar, Neuquén, Patagonia.') },
  'Malma Merlot La Papay': { descripcion: base('Malma Merlot Finca La Papay', 'Malma', 'Merlot', 'Tinto', 'Malma es una bodega patagónica de la región del Río Negro.') },
  'Newen Malbec': { descripcion: base('Newen Malbec', 'Bodega del Fin del Mundo', 'Malbec', 'Tinto', 'Línea Newen (de entrada) de Bodega del Fin del Mundo, San Patricio del Chañar, Neuquén, Patagonia.') },
  'Il Caprone Pinot Noir': { descripcion: base('Il Caprone Pinot Noir', 'Bodegas Bianchi', 'Pinot Noir', 'Tinto', 'Línea de entrada de Bodegas Bianchi, San Rafael, Mendoza.') },
  'Misterio Red Blend': { descripcion: base('Misterio Red Blend', 'Finca Flichman', 'Blend', 'Tinto', 'Línea Misterio de Finca Flichman.') },
  'Finca Flichman Misterio White Malbec': { descripcion: 'Misterio White Malbec es un vino blanco elaborado con uvas Malbec vinificadas en blanco, de la línea Misterio de Finca Flichman.' },
  'Misterio Sweet Chardonnay': { descripcion: base('Misterio Sweet Chardonnay', 'Finca Flichman', 'Chardonnay', 'Blanco', 'Línea Misterio de Finca Flichman, estilo dulce.'), varietalFix: 'Chardonnay' },
  'Varese Limoncello': { descripcion: 'Limoncello Varese es un licor de limón de estilo italiano.' },
  'Vinyes Ocults Blend': { descripcion: base('Vinyes Ocults Blend', 'Vinyes Ocults', 'Blend', 'Tinto') },
  'La Celia Reserva Pinot Grigio': { descripcion: base('La Celia Reserva Pinot Grigio', 'Finca La Celia', 'Pinot Grigio', 'Blanco', 'Finca La Celia, San Rafael, Mendoza.') },
  'Eugenio Bustos Chardonnay': { descripcion: base('Eugenio Bustos Chardonnay', 'Eugenio Bustos', 'Chardonnay', 'Blanco', 'Bodega de San Carlos, Valle de Uco, Mendoza.') },
  'Virgen Cab. Sauv. Orgánico': { descripcion: base('Virgen Cabernet Sauvignon Orgánico', 'Domaine Bousquet', 'Cabernet Sauvignon', 'Tinto', 'Línea Virgen (sin sulfitos agregados) de Domaine Bousquet, bodega orgánica certificada de Tupungato, Valle de Uco, Mendoza.') },
  'Alambrado Cabernet Sauvignon': { descripcion: base('Alambrado Cabernet Sauvignon', 'Santa Julia', 'Cabernet Sauvignon', 'Tinto', 'Línea Alambrado de Santa Julia (Familia Zuccardi), Mendoza.') },
  'Il Caprone Cab. Sauv.': { descripcion: base('Il Caprone Cabernet Sauvignon', 'Bodegas Bianchi', 'Cabernet Sauvignon', 'Tinto', 'Línea de entrada de Bodegas Bianchi, San Rafael, Mendoza.') },
  'Canale Estate Cabernet Franc': { descripcion: base('Canale Estate Cabernet Franc', 'Humberto Canale', 'Cabernet Franc', 'Tinto', 'Bodega Humberto Canale, pionera del Alto Valle de Río Negro, Patagonia.'), bodegaFix: 'Humberto Canale' },
  'Intimo Cabernet Sauvignon': { descripcion: base('Intimo Cabernet Sauvignon', null, 'Cabernet Sauvignon', 'Tinto') },
  'Bodegas Lopez Montchenot 10 años': { descripcion: 'Montchenot 10 años es un vermut añejado de Bodegas López, clásico argentino desde 1898.', categoriaFix: 'Otro', varietalFix: 'Vermouth' },
  'Bodegas Lopez Montchenot 15 años': { descripcion: 'Montchenot 15 años es un vermut añejado de Bodegas López, clásico argentino desde 1898.', categoriaFix: 'Otro', varietalFix: 'Vermouth' },
  'Bodegas Lopez Montchenot 5 años': { descripcion: 'Montchenot 5 años es un vermut añejado de Bodegas López, clásico argentino desde 1898.', categoriaFix: 'Otro', varietalFix: 'Vermouth' },
  'Bodegas Lopez Malbec': { descripcion: base('Bodegas López Malbec', 'Bodegas López', 'Malbec', 'Tinto', 'Bodega mendocina fundada en 1898.') },
  'Plan B Cabernet Sauvignon': { descripcion: base('Plan B Cabernet Sauvignon', null, 'Cabernet Sauvignon', 'Tinto') },
  'Plan B Malbec': { descripcion: base('Plan B Malbec', null, 'Malbec', 'Tinto') },
  'Plan B Blend': { descripcion: base('Plan B Blend', null, 'Blend', 'Tinto'), varietalFix: 'Blend' },
  'Tucumen Bib Malbec': { descripcion: base('Tucumen Malbec', 'Tucumen', 'Malbec', 'Tinto', 'Formato bag-in-box (BiB).') },
  'Tucumen Reserva Malbec': { descripcion: base('Tucumen Reserva Malbec', 'Tucumen', 'Malbec', 'Tinto') },
  'Tucumen Cabernet Sauvignon': { descripcion: base('Tucumen Cabernet Sauvignon', 'Tucumen', 'Cabernet Sauvignon', 'Tinto') },
  'Tucumen Joven Malbec': { descripcion: base('Tucumen Joven Malbec', 'Tucumen', 'Malbec', 'Tinto', 'Estilo joven, de consumo inmediato.') },
  'Tucumen Zinfanel': { descripcion: base('Tucumen Zinfandel', 'Tucumen', 'Zinfandel', 'Tinto'), varietalFix: 'Zinfandel' },
  'Tucumen Cabernet Franc': { descripcion: base('Tucumen Cabernet Franc', 'Tucumen', 'Cabernet Franc', 'Tinto'), varietalFix: 'Cabernet Franc' },
  'Tucumen Ancellota': { descripcion: base('Tucumen Ancellotta', 'Tucumen', 'Ancellotta', 'Tinto'), varietalFix: 'Ancellotta' },
  'Huentala Black Series Chardonnay': { descripcion: base('Huentala Black Series Chardonnay', 'Huentala', 'Chardonnay', 'Blanco', 'Bodega Huentala, Luján de Cuyo, Mendoza.') },
  'Gran Sombrero Cab. Franc Huentala': { descripcion: base('Huentala Gran Sombrero Cabernet Franc', 'Huentala', 'Cabernet Franc', 'Tinto', 'Línea Gran Sombrero de Bodega Huentala, Luján de Cuyo, Mendoza.') },
  'Los Bocheros Malbec Cabernet Franc': { descripcion: base('Los Bocheros Malbec - Cabernet Franc', 'Los Bocheros', 'Blend', 'Tinto', 'Corte de Malbec y Cabernet Franc.') },
  'Zorro Salvaje Cab. Sauv. Huentala': { descripcion: base('Huentala Zorro Salvaje Cabernet Sauvignon', 'Huentala', 'Cabernet Sauvignon', 'Tinto', 'Línea Zorro Salvaje de Bodega Huentala, Luján de Cuyo, Mendoza.') },
  'Gran Sombrero Chardonnay Huentala': { descripcion: base('Huentala Gran Sombrero Chardonnay', 'Huentala', 'Chardonnay', 'Blanco', 'Línea Gran Sombrero de Bodega Huentala, Luján de Cuyo, Mendoza.') },
  'Vinyes Ocults Extra Brut': { descripcion: base('Vinyes Ocults Extra Brut', 'Vinyes Ocults', 'Pinot Noir', 'Espumante'), categoriaFix: 'Espumante', varietalFix: 'Pinot Noir' },
  'Costa y Pampa Extra Brut': { descripcion: 'Costa & Pampa Extra Brut es un espumante elaborado con uvas de la costa atlántica de Chapadmalal, Buenos Aires -- un proyecto vitivinícola atípico en un terroir marítimo.', categoriaFix: 'Espumante' },
  'Bib Piedra Negra Malbec Organic': { descripcion: base('Piedra Negra Malbec Orgánico', 'Piedra Negra', 'Malbec', 'Tinto', 'Formato bag-in-box (BiB). Bodega Piedra Negra, Vista Flores, Valle de Uco, Mendoza, elaborado con uvas de cultivo orgánico.') },
  'Pyros Single Malbec Block 4': { descripcion: base('Pyros Single Malbec Block 4', 'Pyros Wines', 'Malbec', 'Tinto', 'Selección de un bloque específico (Block 4) del viñedo. Pyros Wines, Valle de Uco, Mendoza.') },
  'Pyros Pinot Noir': { descripcion: base('Pyros Pinot Noir', 'Pyros Wines', 'Pinot Noir', 'Tinto', 'Pyros Wines, Valle de Uco, Mendoza, especializada en Pinot Noir de altura.'), varietalFix: 'Pinot Noir' },
  'Casa Boher Agrelo Malbec': { descripcion: base('Casa Boher Agrelo Malbec', 'Petrini', 'Malbec', 'Tinto', 'Línea Casa Boher de Bodega Petrini, de viñedos en Agrelo, Luján de Cuyo, Mendoza.') },
  'Casa Boher Cabernet Sauvignon': { descripcion: base('Casa Boher Cabernet Sauvignon', 'Petrini', 'Cabernet Sauvignon', 'Tinto', 'Línea Casa Boher de Bodega Petrini.') },
  'Casa Boher Cabernet Franc': { descripcion: base('Casa Boher Cabernet Franc', 'Petrini', 'Cabernet Franc', 'Tinto', 'Línea Casa Boher de Bodega Petrini.') },
  'Casa Boher Malbec': { descripcion: base('Casa Boher Malbec', 'Petrini', 'Malbec', 'Tinto', 'Línea Casa Boher de Bodega Petrini.') },
  'Las Perdices Bib Red Blend': { descripcion: base('Las Perdices Red Blend', 'Las Perdices', 'Blend', 'Tinto', 'Formato bag-in-box (BiB). Bodega Las Perdices, Agrelo, Luján de Cuyo, Mendoza.') },
  'Partridge Dulce Las Perdices': { descripcion: base('Las Perdices Partridge Dulce', 'Las Perdices', 'Chardonnay', 'Blanco', 'Línea Partridge de Bodega Las Perdices, estilo dulce.'), varietalFix: 'Chardonnay' },
  'Buenos Hnos. Dulce Natural G. Riili': { descripcion: 'Buenos Hermanos Dulce Natural es un vino de estilo dulce de Bodega Gimenez Riili, de menor graduación de fermentación (vendimia tardía / dulce natural).' },
  'Las Perdices Bib Duo Malbec Cabernet Sauvignon': { descripcion: base('Las Perdices Duo Malbec - Cabernet Sauvignon', 'Las Perdices', 'Blend', 'Tinto', 'Formato bag-in-box (BiB) doble varietal. Bodega Las Perdices, Agrelo, Luján de Cuyo, Mendoza.') },
  'Monte Quieto Alegre Blend': { descripcion: base('Monte Quieto Alegre Blend', 'Monte Quieto', 'Blend', 'Tinto', 'Línea Alegre de Bodega Monte Quieto.') },
  'Latente Cs-Cf': { descripcion: 'Latente Cabernet Sauvignon - Cabernet Franc es un corte tinto de Bodega Cuarto Surco.' },
  'Latente Cs-Mal': { descripcion: 'Latente Cabernet Sauvignon - Malbec es un corte tinto de Bodega Cuarto Surco.' },
  'Tipo Malbec Opend Mind': { descripcion: base('Open Mind Malbec', null, 'Malbec', 'Tinto') },
  'Alta-Yarí Gran Corte': { descripcion: base('Alta-Yarí Gran Corte', 'Alta-Yarí', 'Blend', 'Tinto', 'Línea Gran de Bodega Alta-Yarí.'), varietalFix: 'Blend' },
  'Flor de Manzano Dulce 710': { descripcion: 'Flor de Manzano Dulce es una sidra de manzana de estilo dulce, en botella de 710cc.' },
  'Alta-Yarí Gran Torrontes': { descripcion: base('Alta-Yarí Gran Torrontés', 'Alta-Yarí', 'Torrontés', 'Blanco', 'Línea Gran de Bodega Alta-Yarí.'), varietalFix: 'Torrontés' },
  'Alta-Yarí Reserva Malbec': { descripcion: base('Alta-Yarí Reserva Malbec', 'Alta-Yarí', 'Malbec', 'Tinto', 'Línea Reserva de Bodega Alta-Yarí.'), varietalFix: 'Malbec' },
  'Alta-Yarí Reserva Cabernet Sauvignon': { descripcion: base('Alta-Yarí Reserva Cabernet Sauvignon', 'Alta-Yarí', 'Cabernet Sauvignon', 'Tinto', 'Línea Reserva de Bodega Alta-Yarí.'), varietalFix: 'Cabernet Sauvignon' },
  'Crios Torrontes Susana Balbo': { descripcion: base('Crios Torrontés', 'Susana Balbo Wines', 'Torrontés', 'Blanco', 'Línea Crios de Susana Balbo Wines, Valle de Uco/Agrelo, Mendoza.') },
  'Cruzat Ratafia Chardonnay Est': { descripcion: 'Cruzat Ratafia Chardonnay es un vino generoso/aperitivo espumoso elaborado con Chardonnay, de Bodega Cruzat, especialista mendocina en espumantes por método tradicional.', varietalFix: 'Chardonnay' },
  'Iaccarini Via Blanca Cab. Sauvignon': { descripcion: base('Iaccarini Via Blanca Cabernet Sauvignon', 'Iaccarini', 'Cabernet Sauvignon', 'Tinto', 'Línea Via Blanca de Bodega Iaccarini.') },
  'Acordeón Chardonnay': { descripcion: base('Acordeón Chardonnay', 'Finca Ferrer', 'Chardonnay', 'Blanco', 'Línea Acordeón de Finca Ferrer.') },
  'Diavolezza Montesina': { descripcion: 'Diavolezza es un pisco (aguardiente de uva) de Montesina.' },
  'Abito Rose': { descripcion: base('Abito Rosé', 'Abito', 'Merlot', 'Rosado') },
  'Gualtallary Chardonnay': { descripcion: base('Gualtallary Chardonnay', 'Gualtallary Wines', 'Chardonnay', 'Blanco', 'De viñedos en Gualtallary, Valle de Uco.') },
  'Il Caprone Rose': { descripcion: base('Il Caprone Rosé', 'Bodegas Bianchi', 'Malbec', 'Rosado', 'Línea de entrada de Bodegas Bianchi, San Rafael, Mendoza.') },
  'Tempestad Vermouth': { descripcion: 'Tempestad es un vermut argentino, vino aromatizado con hierbas y especias.' },
}
